### ISSUE TITLE
Nimbus Support?

### ISSUE THREAD

**Issue by pjpalomaki** [xythobuz/Enjoyable#1]
Hey.. I just tested the git.yukkurigames.com/enjoyable.git version and it doesn't work with SteelSeries Nimbus, I've just built this fork but I'm out and don't have the controller with me.. Would this fork work with Nimbus, any idea?

Basically in the git.yukkurigames.com/enjoyable.git only sticks and a couple of buttons are recognised.

Thanks,
PJ

**Comment by xythobuz** [comment]
Sorry, I haven't actually done anything that has to do with Enjoyables controller support. Only some cosmetic changes. So there should be no difference to the upstream repository.

However, as far as I understand, if your controller works or not should not have anything to do with Enjoyable, as it will work with any gamepad-like USB Human Interface Device.

> Basically in the git.yukkurigames.com/enjoyable.git only sticks and a couple of buttons are recognised.

So, buttons and axes work? What is not working, then? My standard gamepads don't have anything else... :)
